### ISSUE TITLE
Elements offset in Kiwi

### ISSUE THREAD

**Issue by TheHypnotist333** [prettierlichess/prettierlichess#131] opened 2022-12-28 11:32 UTC
Everything looks fine while playing a game but afterwards in the post-game analysis page everything is off screen to the left. Same issue when trying to view any completed games.
This started happening to me a few weeks ago, before that I never had the problem
![Screenshot_20221228-063048](https://user-images.githubusercontent.com/104811236/209805740-39ddefa4-5aa3-43da-ad57-8e4f6b9ba565.png)
![Screenshot_20221228-063113](https://user-images.githubusercontent.com/104811236/209805755-94e7c165-4d6e-4400-8ea4-29ca0b8c7933.png)

**Comment by kieferro** [comment] 2022-12-28 12:14
Thank you for reporting this bug. I can reproduce the problem with the current released version of the extension. But this problem seems to be caused by the same bug as #130 and should be resolved by e0d616866eecb36f4f6c4eaa50e01ee75d3135b9.
We will publish an update soon. If you still have this problem with a version higher than `3.6.1`, please reopen.

**Closed by kieferro** 2022-12-28 12:14 UTC
Labels: bug
