### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by Paul0o7** [prettierlichess/prettierlichess#139] opened 2023-02-12 21:19 UTC
![image](https://user-images.githubusercontent.com/120352783/218337840-3a256761-d537-407f-958b-947f18830035.png)

**Comment by kieferro** [comment] 2023-02-12 21:34
What exactly is the bug supposed to be? I can't see anything wrong with this picture. I'd need more information to be able to help. Thanks

**Comment by Paul0o7** [comment] 2023-02-13 02:20
It changed From normal like the site showed to this where the board is on the right side and the select on the left

**Comment by kieferro** [comment] 2023-02-13 22:16
Below a certain screen width, only matchmaking and Lichess TV are displayed and not the arena/event overview. This is both intentional and standard Lichess behavior. Also that the current game is displayed on the left is intentional and a stylistic decision.

If you haven't changed your screen or your screen settings it's a bit odd though that the layout would change. But I don't really understand what the problem is with that. Does it limit you in any way or make features unusable? And what kind of arrangement would you prefer?

**Comment by kieferro** [comment] 2023-02-20 22:09
I'm going to close this for now. As I said, I would like to help you, but I need more information. So feel free to open again if you have any more information or questions.

**Closed by kieferro** 2023-02-20 22:09 UTC
