### ISSUE TITLE
Windows are out of order

### ISSUE THREAD

**Issue by Pawnstreetblues** [prettierlichess/prettierlichess#155] opened 2023-05-12 08:12 UTC
Lichess had an update and immediately after the windows look like this:
![Screenshot 2023-05-11 222632](https://github.com/prettierlichess/prettierlichess/assets/106215734/025a2c81-93a8-4334-8c51-b78f7f2003b5)

**Comment by kieferro** [comment] 2023-05-12 08:21
Thank you for reporting this. This is a duplicate of #154

**Closed by kieferro** 2023-05-12 08:21 UTC
Labels: duplicate

**Comment by kieferro** [comment] 2023-05-14 15:00
The patch has been released and is available since yesterday for Firefox and Chrome under version 3.8.2. Please update the extension if this has not already happened automatically.
