### ISSUE TITLE
Board is oversized AGAIN when I'm going full-screen 

### ISSUE THREAD

**Issue by Swapneel415** [prettierlichess/prettierlichess#180] opened 2023-07-28 12:43 UTC
The title and this screenshot https://prnt.sc/SiQHHRr_YUxK says it all:
Why is the board so oversized? Can't it be made to fit on the page without making the text and other info narrower? And without making the board size (in % from Preferences) smaller?
Thanks

**Comment by kieferro** [comment] 2023-07-29 18:52
Thanks for reporting. I assume you are already using the 1080p layout setting instead of the 1440p one?

To really fix the problem permanently, it would be quite good to know your screen resolution. Then I can reproduce the view locally.
Also: are you using any special mode or why is the top bar not visible?

**Comment by Swapneel415** [comment] 2023-07-30 10:28
> 
> To really fix the problem permanently, it would be quite good to know your screen resolution. Then I can reproduce the view locally. Also: are you using any special mode or why is the top bar not visible?
I'm using full-screen in Lichess here. Just click the three dots in chrome at the top right corner just below the 'cross' button and click 'fullscreen' button beside the 'zoom' option.  My display resolution is 1440 x 900. I just adjusted and cropped the screenshot to not include the top bar.

**Comment by kieferro** [comment] 2023-07-31 18:47
Okay, I managed to replicate your setup, but I couldn't really replicate the problem. For me, the board size is the same whether I use the extension or not. If you increase the size of the board (e.g. in the analysis view), the extension will of course not overwrite it. So could you please take two screenshots (preferably not cropped - if you are worried about your username being seen you can of course do this in incognito mode), one with the extension and one without, so I can see what effect the extension has on the size of the board. Sorry to bother you with so many follow-up requests, but it's the only way I can really understand the underlying problem.

**Comment by Swapneel415** [comment] 2023-08-01 13:07
The screenshots are:
https://prnt.sc/y_JVcLliMD5X - with the extension
https://prnt.sc/askdsCDQX9Fe - without the extension 
Both have the 100% board size, which is oversized here. I'm currently using 87% board size to keep the side info large (and broad) enough.

**Comment by kieferro** [comment] 2023-08-01 13:50
I don't understand. The board has the same size in both pictures. So clearly the size of the board is not changed by the extension, it is the size the board already has at lichess without the extension. If you have a bug that makes the board appear larger than it should be, you need to report it to lichess, not here, as it doesn't seem to be caused by the prettierlichess extension.

**Comment by kieferro** [comment] 2023-09-15 11:45
I'm going to close this for now. If you have any questions or more information, feel free to reopen.

**Closed by kieferro** 2023-09-15 11:45 UTC
