### ISSUE TITLE
Please fix this (duplicate)

### ISSUE THREAD

**Issue by Pawnstreetblues** [prettierlichess/prettierlichess#158] opened 2023-05-13 00:32 UTC
![237911220-025a2c81-93a8-4334-8c51-b78f7f2003b5 (1)](https://github.com/prettierlichess/prettierlichess/assets/106215734/44d7f518-188e-4d18-a739-db9cbef25fd1)

I cant play like this, and I want to use prettier lichess, is there any progress in getting it fixed?  Wish you all the luck to fix it, thank you.

**Comment by muon8025** [comment] 2023-05-13 15:47
I have the same issue!
![lichess bug](https://github.com/prettierlichess/prettierlichess/assets/58478451/85f82113-ac5f-4d95-850b-f7fa1f60ec76)

**Comment by kieferro** [comment] 2023-05-14 15:06
Duplicate of #154

The patch has been released and is available since yesterday for Firefox and Chrome under version 3.8.2. Please update the extension if this has not already happened automatically.

> I cant play like this, and I want to use prettier lichess, is there any progress in getting it fixed? Wish you all the luck to fix it, thank you.

Sometimes, there are updates for Lichess that break the extension. Unfortunately it takes some time until the release of the patches is unlocked in the stores.

**Closed by kieferro** 2023-05-14 15:06 UTC
