### ISSUE TITLE
eval bar mess up the board

### ISSUE THREAD

**Issue by neumannhugo** [prettierlichess/prettierlichess#34] opened 2021-05-02 00:26 UTC
there is a bug, when you turn on the evalbar and after turning it off, moving the pieces is bugged, grabbing them are shifted by the width of the evalbar.

**Comment by noahsemus** [comment] 2021-05-11 15:14
Duplicate of [issue #33](https://github.com/prettierlichess/prettierlichess/issues/33).

**Closed** 2021-05-11 15:14 UTC
