### ISSUE TITLE
Analysis Board

### ISSUE THREAD

**Issue by ThomasLatrat** [prettierlichess/prettierlichess#216] opened 2024-04-28 10:59 UTC
When Analysis Board is opened from menu, the board is small. 
![image](https://github.com/prettierlichess/prettierlichess/assets/97710322/e854b68c-f7f2-4d61-9e8e-d162a0b8b7f7)

**Comment by kieferro** [comment] 2024-04-28 15:23
Thanks for reporting, duplicate of #214

**Closed by kieferro** 2024-04-28 15:23 UTC
Labels: duplicate
