### ISSUE TITLE
Weird time panel

### ISSUE THREAD

**Issue by naturallyfroggy** [prettierlichess/prettierlichess#157] opened 2023-05-13 00:24 UTC
![Screenshot (5)](https://github.com/prettierlichess/prettierlichess/assets/133459351/a7993c03-9389-48d9-99fa-b20622d7e0af)

**Comment by Pawnstreetblues** [comment] 2023-05-13 01:48
it started immediately after lichess refreshed last night

**Comment by Sires0** [comment] 2023-05-13 13:03
Also getting this

**Comment by kieferro** [comment] 2023-05-14 15:02
Duplicate of #154

The patch has been released and is available since yesterday for Firefox and Chrome under version 3.8.2. Please update the extension if this has not already happened automatically.

**Closed by kieferro** 2023-05-14 15:02 UTC
Labels: duplicate
