### ISSUE TITLE
Install on load unpacked

### ISSUE THREAD

**Issue by Aspect-Arch** [prettierlichess/prettierlichess#135] opened 2023-01-30 05:13 UTC
So my school blocked chrome web store so i was trying to install the extension manually. I downloaded the files from this repo and I extracted it into a folder. I then tried to load it as an extension using dev mode on chrome and it said there was no manifest file. Anyone know how to fox it? 

Thanks in advance :)

**Comment by kieferro** [comment] 2023-01-31 00:12
Thanks for the question. Your approach is correct in itself, but the problem is that this project uses webpack as a module bundler. This means you have to do a build first to get a working version. I have attached a [working build to the latest release](https://github.com/prettierlichess/prettierlichess/releases/download/v.3.7.1/build-3.7.1.zip) that you can download and then use.

The releases will always include a build version in the future as well (#136).

**Comment by kieferro** [comment] 2023-01-31 00:12
I'll close this for now. If you still have questions, feel free to reopen.

**Closed by kieferro** 2023-01-31 00:12 UTC
Labels: question

**Comment by Aspect-Arch** [comment] 2023-02-05 18:57
ok ty. it worked
