### ISSUE TITLE
Donate button misaligned

### ISSUE THREAD

**Issue by ivanmironov** [prettierlichess/prettierlichess#128] opened 2022-12-20 03:10 UTC
The Donate button in the top left corner (visible on the homepage of the website as a golden link) is not clickable when the mouse is hovered directly over it. Instead, the mouse has to be positioned slightly lower than the Donate button to click it. 
![image](https://user-images.githubusercontent.com/25747397/208572539-227aca12-e3ac-4e56-944d-120b2a3b476b.png)

**Comment by kieferro** [comment] 2022-12-20 06:52
Thank you for reporting the bug. This is a duplicate of #126 and already fixed. We will roll out a patch soon

**Closed by kieferro** 2022-12-20 06:52 UTC
