### ISSUE TITLE
Gui being glitchy

### ISSUE THREAD

**Issue by atriup** [prettierlichess/prettierlichess#159] opened 2023-05-13 16:00 UTC
When applying the extension and playing a game, the menu on the right side of the board that shows the player names, time and moves played is misplaced and glitchy. I am using brave, on the latest version of the extension.

![Inked238145257-4bcd607e-ea6f-4180-8bbe-1c4bcdd6119a](https://github.com/prettierlichess/prettierlichess/assets/131788637/7e29282e-8fda-4632-a0b0-0198b6c97728)

**Comment by kieferro** [comment] 2023-05-14 15:02
Duplicate of #154

The patch has been released and is available since yesterday for Firefox and Chrome under version 3.8.2. Please update the extension if this has not already happened automatically.

**Closed by kieferro** 2023-05-14 15:02 UTC
